### ISSUE TITLE
Linked files and other things not working when deployed to a custom domain.

### ISSUE THREAD

**Issue by dsaderholm** [BinBashBanana/pywb-test#5] opened 2020-09-26 21:33 UTC
If I deploy it to Heroku with no domain it works fine, but when I add a domain websites don't show correctly.

**Comment by BinBashBanana** [comment] 2020-09-26 23:55
Yes, that's an issue that I'm working on. Although they seem to work fine over HTTP, the problem is with the certificate.

**Comment by BinBashBanana** [comment] 2021-02-13 06:23
Fixed now!

**Closed as completed by BinBashBanana** 2021-02-13 06:23 UTC
